version: '1.0'

services: 
  backend:
    build:
      context: .  # Dockerfile joylashgan papka
    container_name: backend
    env_file: 
      - .env
    volumes:
      - .:/usr/local/app
    ports:
      - "4000:4000"
    networks:
      - backend_network
    depends_on:
      - redis
      - postgres
    restart: always

  redis:
    image: redis:7-alpine  # Redis rasmidan foydalanish
    container_name: redis
    ports:
      - "6379:6379"  # Redis portini ochish
    networks:
      - backend_network
    restart: always

  postgres:
    image: postgres:15-alpine  # PostgreSQL rasmidan foydalanish
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"  # PostgreSQL portini ochish
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Ma'lumotlarni saqlash
    networks:
      - backend_network
    restart: always

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
