version: '1.0'

services: 
  backend:
    image: node:18-alpine
    container_name: feane
    env_file: 
      - .env  # .env faylini konteynerga yuklash
    working_dir: /app  # Konteynerdagi ishchi katalog
    volumes:
      - ./:/app  # Joriy papkani konteynerga /app sifatida bog'lash
    command: sh -c "npm install reflect-metadata@^0.2.2 --legacy-peer-deps && npm run start"  # Kerakli paketlarni o'rnatish va ishga tushurish
    ports:
      - "4000:4000"  # Portni ochish
    networks:
      - backend_network  # Tarmoqni yaratish va unga ulanish
    restart: always  # Avtomatik qayta ishga tushirish

networks:
  backend_network:
    driver: bridge
